engines:
  duplication:
    enabled: true
    config:
      languages:
      - php:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
    - 'src/**/*.php'
exclude_paths:
  - 'tests/*'
  - RoboFile.php
