build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          - command: phpcs-run
            use_website_config: true
      environment:
        node:
          version: 6.0.0
filter:
  excluded_paths:
    - 'tests/*'
    - RoboFile.php
checks:
  php: true
coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
